# Generated by Django 6.0.3 on 2026-04-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appTwo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
